name: Build Sundials and Models

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-sundials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install General Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libopenmpi-dev
          # Installs CMake, G++, Make, and OpenMPI

      - name: Install SWIG
        run: sudo apt-get install -y swig

      - name: Install OpenMP
        run: sudo apt-get install -y libomp-dev
        # This installs the OpenMP library

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.14
        id: cuda-toolkit
        with:
          cuda: "12.0.0"
          use-github-cache: false

      - name: Check NVCC Version
        run: nvcc -V

      - name: Download Sundials
        run: |
          wget https://github.com/LLNL/sundials/releases/download/v6.7.0/sundials-6.7.0.tar.gz -O sundials-6.7.0.tar.gz
          tar -xzvf sundials-6.7.0.tar.gz

      - name: Build Sundials
        run: |
          mkdir -p sundials-build
          cd sundials-build
          cmake ../sundials-5.7.0 -DBUILD_SHARED_LIBS=ON -DEXAMPLES_INSTALL_PATH=${GITHUB_WORKSPACE}/sundials-examples
          make
          sudo make install

      - name: Upload Sundials Build
        uses: actions/upload-artifact@v2
        with:
          name: sundials-build
          path: sundials-build
